#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Iterable


ROOT = Path(__file__).resolve().parents[4]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from minimal_shot_av.model.wod_e2e import _import_official_parser


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a local WOD-E2E frame-list JSON from TFRecord shards."
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=ROOT / "workspace" / "waymo_open_dataset_end_to_end_camera_v_1_0_0" / "test",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "data" / "waymo" / "e2e" / "submission_frames" / "test_frames.local.json",
    )
    parser.add_argument("--max-shards", type=int)
    parser.add_argument("--max-records", type=int)
    args = parser.parse_args()

    names = list(iter_frame_names(args.data_dir, max_shards=args.max_shards, max_records=args.max_records))
    payload = frame_list_payload(names, source=str(args.data_dir))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(args.output), "frame_count": len(names)}, indent=2, sort_keys=True))
    return 0


def iter_frame_names(
    data_dir: Path,
    *,
    max_shards: int | None = None,
    max_records: int | None = None,
) -> Iterable[str]:
    tf, wod_e2ed_pb2 = _import_official_parser()
    shards = sorted(data_dir.glob("*.tfrecord-*"))
    if not shards:
        raise FileNotFoundError(f"no WOD-E2E shards found under {data_dir}")
    if max_shards is not None:
        shards = shards[:max_shards]

    records_seen = 0
    for shard in shards:
        dataset = tf.data.TFRecordDataset([str(shard)], compression_type="")
        for record in dataset:
            records_seen += 1
            if max_records is not None and records_seen > max_records:
                return
            frame = wod_e2ed_pb2.E2EDFrame()
            frame.ParseFromString(record.numpy())
            frame_name = str(frame.frame.context.name)
            if frame_name:
                yield frame_name


def frame_list_payload(frame_names: list[str], *, source: str) -> dict[str, object]:
    duplicates = sorted({name for name in frame_names if frame_names.count(name) > 1})
    if duplicates:
        preview = ", ".join(duplicates[:5])
        raise ValueError(f"duplicate frame names found: {preview}")
    return {
        "source": source,
        "official_challenge_frame_list": False,
        "frame_count": len(frame_names),
        "frame_names": sorted(frame_names),
        "note": (
            "Local frame list generated by enumerating WOD-E2E TFRecords. "
            "Use the official challenge-provided JSON for leaderboard submission when available."
        ),
    }


if __name__ == "__main__":
    raise SystemExit(main())
